### ISSUE TITLE
Increase space between paragraphs

### ISSUE THREAD

**Issue by tthuem** [SoftVarE-Group/SlideTemplate#16]
Currently, we often use \medskip, \bigskip, \\[1.5ex], or \\[2ex] in slides. It would significantly simplify the source for slides and, thus, their creation and maintenance, if the standard space between paragraphs could be increased to a useful value. Hence, an empty line in the source would be sufficient to have such space.

**Comment by tthuem** [comment]
Please check what happens for \begin{center}...\end{center} (also itemize, enumerate) environments. Ideally, they do not add any extra space then compared to a simple line without any environment.

**Comment by Benno2000** [comment]
I set the parskip to 1.5ex for the whole document including minipages and tcolorboxes. (See commit from above) Is this amount of parksip ok?

**Comment by tthuem** [comment]
Do you have an example illustrating the parskip between different elements?

**Comment by Benno2000** [comment]
You should be able to see it in the committed PDF file.

**Comment by tthuem** [comment]
Looks good in general, but seems to have some undesired side-effects.

1. Titles in mydefinition/example/note use more space now.

![grafik](https://user-images.githubusercontent.com/5330357/159223822-066a3dd4-4b7f-42dc-b778-78ed3adc0e80.png)

2. The contents listing consumes also more space.

![grafik](https://user-images.githubusercontent.com/5330357/159223909-3f927e41-222a-4185-adeb-4bde9b6cb3fc.png)

Would be good if you could check the demo document side-by-side with the old version to study other side effects and find a solution.

**Comment by Benno2000** [comment]
1. I don't see any difference between the version with (left) and without the new parskip (right). I just set the parskip for the content of the tcolorbox and not for the title.
<img width="1398" alt="Bildschirmfoto 2022-03-21 um 12 02 57" src="https://user-images.githubusercontent.com/23581917/159249711-92d1970b-eb05-4789-b2cb-8200f117762e.png">

2. Should they just have the same parskip as before (no parskip)? (right)
<img width="1399" alt="Bildschirmfoto 2022-03-21 um 12 03 57" src="https://user-images.githubusercontent.com/23581917/159249905-b2c854c5-8a17-49c3-93c4-eaa59814966b.png">

**Comment by tthuem** [comment]
1. Maybe you have made other changes on the branch causing the effect then? Or is it really different behavior on my machine?

2. Yes.

**Comment by Benno2000** [comment]
1. I think this comes from the `\strut` in front of the title which is used to get a uniform title height. Technically, the title should be centered, but when there are no letters that go below the baseline (like in "A Test"), it looks as if is de-centered. 
With `\vphantom{/}` (left) instead of `\strut` (right) it looks a little more condensed:
<img width="611" alt="Bildschirmfoto 2022-03-21 um 17 16 55" src="https://user-images.githubusercontent.com/23581917/159304240-593329e0-f4f7-4bae-b27a-734bcf363234.png">

**Comment by Benno2000** [comment]
2. The linespacing could be reset directly before the toc is generated in `\AtBeginSection`. In this case we would additionally need something like a `\lectureoverview`-command to create the lecture overview at the end also with zero line spacing which is now manually created in the example file.

**Comment by tthuem** [comment]
Done
