### ISSUE TITLE
Improve compilation time of slides

### ISSUE THREAD

**Issue by tthuem** [SoftVarE-Group/SlideTemplate#17]
Currently, typical slides take about a minute compilation time on my machine. That is way too slow to layout slides. Here are a number of ideas to achieve a speedup:

1. We could introduce a draft mode that is faster by simplifying the template or so. Is there already a draft mode for our template?
2. Check which slides need most computation time. The title slide? Slides with tikz? Slides with listings?
3. Significantly simplify our template and analyze what consumes most time. Header? Footer?
4. We could split slides into three parts and add those as PDF with overlay for the page numbers (could also be helpful to create the PDF with slides for all lectures). Problem here would be that jumps within a lecture but across parts are hardly feasible.
5. We could include certain parts of the slides (e.g., pictures, listings) by creating a PDF separately and including this. I know that it is even feasible with latex to only regenerate those pdfs if the source for them has changed.
6. We could use include and includeonly to omit parts that are not relevant for the current editing.

**Comment by tthuem** [comment]
The new template is much faster already, especially due to limiting the use of Tikz. With the includeonlyframes in our example, I do not think we need any further speedups.

**Comment by Benno2000** [comment]
I added an example for the use of `\includeonlyframes{}` to the demo slides in 78738e3209dd0262f3793e81f04f9adc8def31f2.
