### ISSUE TITLE
Add possibility to set and trim title picture

### ISSUE THREAD

**Issue by Benno2000** [SoftVarE-Group/SlideTemplate#19]
It should be possible to set the picture on the title page and move it to get the wanted crop. If no picture is defined, a default picture or no picture should be set.

**Comment by Benno2000** [comment]
Renewed \maketitle and added two optional parameters for image and trimming. If no image is set, a default image is used. The title bar is now at the bottom. The logo bar is bigger now and not part of the footer anymore.
<img width="668" alt="Bildschirmfoto 2022-03-07 um 17 34 05" src="https://user-images.githubusercontent.com/23581917/157076739-ce558f1b-135d-4a9e-8f84-26a2ce8a75d3.png">

**Comment by tthuem** [comment]
Looks great, thanks!
