### ISSUE TITLE
Avoid Weird Problem When Using , in Title of mydefinition, mynote, myexample

### ISSUE THREAD

**Issue by tthuem** [SoftVarE-Group/SlideTemplate#2]
Currently, there need to be {braces} around every title that uses a comma. Otherwise, the slides will not compile.

**Comment by Benno2000** [comment]
The {braces} could just be put into the template, then it works:
`\newcommand{\mydefinition}[2]{
	\begin{tcolorbox}[title={#1},colback=orange!10,colframe=orange!30,coltitle=black,fonttitle=\bfseries,left=1mm,right=1mm,top=1mm,bottom=1mm]
		#2
	\end{tcolorbox}
}`

**Comment by tthuem** [comment]
Great, then lets do this! :)
