### ISSUE TITLE
Add starting slide for sections

### ISSUE THREAD

**Issue by Benno2000** [SoftVarE-Group/SlideTemplate#20]
At the begin of each section, an overview about all sections should be displayed. 
The subsections of the current section should only be displayed in handout mode.

**Comment by Benno2000** [comment]
Added starting slide for sections which contains a table of contents with the current section highlighted. The toc only shows the subsection of the current section. The frame does not have a footer and title.

<img width="667" alt="Bildschirmfoto 2022-03-07 um 16 26 17" src="https://user-images.githubusercontent.com/23581917/157063957-6b1319ce-f261-4339-9504-c1d24f66fa36.png">

**Comment by tthuem** [comment]
I would prefer having a footer on that slide.
