### ISSUE TITLE
Make Subtitles Optional

### ISSUE THREAD

**Issue by tthuem** [SoftVarE-Group/SlideTemplate#23]
Currently title page and footer look weird when no subtitle is defined.

![grafik](https://user-images.githubusercontent.com/5330357/157902954-ec4b480a-02a8-4822-a99b-1906d8dbe90c.png)

![grafik](https://user-images.githubusercontent.com/5330357/157903039-98be989f-1a39-4f6d-9c2c-3c0cfc19992c.png)

**Comment by Benno2000** [comment]
Subtitles are now optional.

<img width="667" alt="Bildschirmfoto 2022-03-15 um 11 37 04" src="https://user-images.githubusercontent.com/23581917/158359696-9f9c0510-bdad-488a-82c3-3eb5b6f0c4bd.png">
