### ISSUE TITLE
Make Content Layouts Verbatim-Safe

### ISSUE THREAD

**Issue by Benno2000** [SoftVarE-Group/SlideTemplate#26]
Currently verbatim environments like `lstlisting` do not work inside content layouts like `\leftandright`.

**Comment by EagleoutIce** [comment]
See https://github.com/EagleoutIce/SlideTemplate/pull/7 for a solution. 
I have documented each macro added with great care.

Is there any reason for the concrete implementation 'partofpage'?
Why did you decide against beamers column mechanism which can do all that and much more?

**Comment by tthuem** [comment]
I have not yet used beamers column mechanism. @Benno2000, do you want to have a look at it?

A drawback of the environments is that it is slightly more complicated to change the layout, which I frequently do when drafting slides. A sophisticated editor would eliminate this problem, but TeXstudio does not support a renaming of the end tag properly.

Another solution could be to prerender the listings and then just add them. However, I understand that this is more complicated if there are numerous listings.

**Comment by EagleoutIce** [comment]
Using columns is rather easy:

```latex
\begin{columns}[c,onlytextwidth]
  \column<2->{.5\linewidth}
  Verbatim-Safe Content
  \column<3->{.25\linewidth}
  Another Block of Verbatim-Safe Content
  \column{.25\linewidth}
  And jet, another Block of Verbatim-Safe Content
\end{columns}
```

The option `onlytextwidth` is short for `totalwidth=\textwidth` and can be passed as a class option (see 12.7 of the beamer documentation). 
As you can see, all of the columns can also be combined with overlay specifications (and they can be used with `\begin{column}{0.5\linewidth}...\end{column}` as well).

Internally, columns rely on minipages (but automatically account for margins, spaces aligns etc.). If you are interested in their implementation, see [here](https://github.com/josephwright/beamer/blob/c171ed2c6abfc2fb99378a0cf8655981cef0b855/base/beamerbaseframecomponents.sty#L253).

As my [PR](https://github.com/EagleoutIce/SlideTemplate/pull/7) keeps the old behavior with `\leftthenright{...}{...}` completely intact, 
it is only necessary to adapt `\partofpage`  and wrap its use in a column environment (or use the linked beamer implementation as a basis to correctly initialize the minipage.
However, at least in my opinion, the new verbatim-safe way of calling these split-layouts is better:

```latex
\begin{leftthenright}
 % left
\second
 % right
\end{leftthenright}
```

as they keep the abstraction and allow to change the layout easily, while being verbatim safe, easily creatable and modifiable with the internal `\uulm@CreateSplitterBox`. As this macro always creates both version i consider it to be a good compromise: 
for all default splits you can use the old way of writing: `\leftthenright{...}{...}` and whenever necessary (verbatim content, catcode-magic etc.) you can switch to the similarly named environment.


If the listings are not to be automated, you can use either boxes to alleviate the problem with the layout (but requiring environments again and being unable to change the listings content based on the frame easily).
Or you could rely on `\inputminted` (or the similar listings command).

However if it is of the utmost importance to use catcode-magic within `\leftthenright` i can recreate those macros to perform necessary preprocessing (e.g. faking the groups). However, this requires some tex-hackery.

**Comment by EagleoutIce** [comment]
If you want, i can create a PR  on this repository and we can discuss possible adaptions there.

**Comment by tthuem** [comment]
I just discussed this together with Benno and we have the following proposal:

\begin{mycolumns}[]
% left
\mynextcolumn
% right
\end{mycolumns}

Then options to have more than two columns and for other animations (i.e., leftandright, leftorright), whereas leftthenright is the default.

**Comment by tthuem** [comment]
Please do not remove any existing commands, but rather make them deprecated (e.g., add them as deprecated in the example).

**Comment by EagleoutIce** [comment]
The current implementation proposed is very similar.
  Is it necessary to prefix all of this with `my`?
  
  Furthermore, I decided to use `\second` and `\third` as markers to split the columns, but that can be changed.
  
  @tthuem do you prefer using `\begin{mycolumns}[leftthenright]` over `\begin{leftthenright}`?

**Comment by tthuem** [comment]
Do you have another solution to avoid name clashes with other packages? Users of the template are likely to add further package imports that we are not aware of. Finding solutions then could be laborous.

\second and \third would also be fine with me (if we can avoid name clashes).

The idea of a single environment was that it is easier to change the animation, as it is simply a flag passed as parameter. Also, this gives the effect that you first focus on content and then can add animations later on. We can also easily have a default animation that is reasonable for most users (e.g., leftthenright).
