### ISSUE TITLE
New option to disable the institute logo or replace it with another one

### ISSUE THREAD

**Issue by tthuem** [SoftVarE-Group/SlideTemplate#27]
For student presentations, it would be good if the default has no institute logo at all. The example could contain a line to add it, which is commented out.

**Comment by EagleoutIce** [comment]
@Benno2000 if you want to, i can do this issue.

**Comment by tthuem** [comment]
Ideally, one could replace both logos with particular commands (i.e., also the university logo).

@EagleoutIce Sounds good. :)

**Comment by tthuem** [comment]
Works great!
