### ISSUE TITLE
Customizable colored boxes

### ISSUE THREAD

**Issue by tthuem** [SoftVarE-Group/SlideTemplate#29]
Currently, we have defined boxes for definition, example, and note. I could imagine that we create a command that gives users the possibility to create such commands easily, by just providing the name and the color. However, I am not sure whether this is feasible.

**Comment by EagleoutIce** [comment]
Internally, this is done by https://github.com/EagleoutIce/SlideTemplate/pull/7 with the internal macro: `\uulm@MakeNewBox`
This macro can be promoted to user-level by a simple `\let\MakeNewBox\uulm@MakeNewBox` (or any other, better name :D).

The macro as implemented has one downside: it can only change macros where the major box exists (e.g. definition) and the tight version (e.g. definitiontight) does not. Futhermore, it always creates the `\myX` macro  and the `X` environment (which allowed the linked PR to be backwards-compatible).

However, this can be dealt with easily by checking the existence of these macros/environments prior to their definition ans use `\newY` and `\renewY` accordingly (there is also a comment regarding that in the code).

**Comment by tthuem** [comment]
I have played around with this but was not able to define new environments outside of the template (e.g., in the example file).
