### ISSUE TITLE
Fitbox produces wrong alignment for titles

### ISSUE THREAD

**Issue by EagleoutIce** [SoftVarE-Group/SlideTemplate#30]
The current implementation of `\fitbox` has unwanted side-effects:
```latex
\setbeamertemplate{frametitle}{
    \vspace{20pt}%
    \fitbox[maxheight=2.5ex,minheight=0pt,maxwidth=\textwidth,minwidth=0pt]{%
        \vphantom{/}\insertframetitle{}%
    }%
}
```
1. You can not use `\hfill` to place parts of the title on the right (e.g. with continued slides, or web-references)
2. When titles are scaled, their baselines do no longer align
3. Downscaling in height destroys their alignment.

![Screenshot_20220725_004607](https://user-images.githubusercontent.com/9303573/180669191-873a193f-c4e1-4195-9292-15bfab68c0f9.png)

Currently, I use the following fix, which relies on `\resizebox` (which is part of graphics/graphicx and therefore already imported most of the time):

```latex
\setbeamertemplate{frametitle}{
    \vspace{20pt}%
    \setbox0=\hbox{\insertframetitle}%
    \ifdim\wd0<\textwidth
    \insertframetitle
    \else\let\hfill\space\resizebox\linewidth!{\insertframetitle}\fi
}
```

This definition differs in that it does no longer respect the height of the title. However, if title elements are high enough to reach into the main-text they should be dealt with manually (e.g. by smashing them).

![Screenshot_20220725_004627](https://user-images.githubusercontent.com/9303573/180669194-2ed1bf2a-6f11-458f-b16d-85d628ceb09e.png)

**Comment by tthuem** [comment]
Furthermore, it seems that there is no margin between the title and the content (even without scaling). Hence, if there is a lot of content on a slide, it hits the baseline of the font, which is pretty annoying. I would propose to move the title a bit upwards, as this would not affect any existing slides (i.e., content does not have to be realigned.

**Comment by EagleoutIce** [comment]
@Benno2000 wants to do this.
