### ISSUE TITLE
Use multiple columns for lectureoverview and rename command

### ISSUE THREAD

**Issue by Benno2000** [SoftVarE-Group/SlideTemplate#38]
To fit long lecture overviews on a single slide, multiple columns should be used. The command `\lectureoverview` should also be renamed to something more general.

**Comment by EagleoutIce** [comment]
We already have multiple columns. See https://github.com/EagleoutIce/SlideTemplate/pull/2 and https://github.com/EagleoutIce/SlideTemplate/pull/3.

**Comment by Benno2000** [comment]
When i compile the demoslides on the main branch, i don't get multiple columns in the lecture overview. I added the multicols environment to the `\lectureoverview`-command in https://github.com/SoftVarE-Group/SlideTemplate/commit/d33b03bdd9330888b2e7fac9d7687badb140c6fd.

@tthuem In our meeting we discussed that a new, more general name should be used instead of `\lectureoverview`. Do you agree with `\contentoverview` as a new name? I would keep the old name in addition (and mark it as deprecated) to keep the template backwards compatible with old slides.

**Comment by tthuem** [comment]
Sounds good to me.

**Comment by Benno2000** [comment]
I changed `\lectureoverview` to `\contentoverview` in 0f47b29cf28338933c77a9a9a4e3eb03fbd05107. The old command is still usable but marked as deprecated in the template file as well as in the demo slides.

Content overview slides now look like this:

![Bildschirmfoto 2022-09-09 um 17 06 46](https://user-images.githubusercontent.com/23581917/189382430-3872e527-3879-40e3-b3cd-bba65495407f.jpg)

**Comment by tthuem** [comment]
Can we increase spaces between lines here? Especially in front of new section names?

**Comment by Benno2000** [comment]
For now I did only manage to control the space for all lines (using `\setlength{\parskip}{...}`) but I'll see if I can find a way to inrease only the space after each section.

**Comment by Benno2000** [comment]
I increased the toc parskip in c2c9b91097fc442a5e28e21009251d5cf7c78c4a so 3 sections with 8 subsections each fit on the content overview slide. However this is not optimal as it needs a lot of space and some spacings are still rather dense:

![Bildschirmfoto 2022-09-13 um 11 53 57](https://user-images.githubusercontent.com/23581917/189871464-5f883f99-2d41-4d80-b98d-6164813ea610.png)

I found a way to [increase only the space after each section via the tocloft package](https://tex.stackexchange.com/questions/56546/how-to-change-spaces-between-items-in-table-of-contents) however using the package causes errors.

**Comment by tthuem** [comment]
I have moved this to the next milestone, as I do have a workaround for now:

`\addtocontents{toc}{\vspace{5mm}`

Would be nice if we could add this automatically between sections. Maybe using 'AtBeginSection`or so.

**Comment by tthuem** [comment]
Fixed in [09e48be](https://github.com/SoftVarE-Group/SlideTemplate/commit/09e48be6c5de5a1b1ccb2a8421c6a01ff1f47302)
