### ISSUE TITLE
Autoref Label for Slides

### ISSUE THREAD

**Issue by tthuem** [SoftVarE-Group/SlideTemplate#4]
Autoref has no label for slides: Slide~\ref{frame:scientific-contributions} used as workaround, but wanted \autoref{frame:scientific-contributions}

**Comment by Benno2000** [comment]
Even after searching for a while i couldn't find any possible solution to this problem, it seems like beamer does not let you set the autoref-label for frames. The only solution would be to use `cref` instead auf `autoref` which modifies `\label` to take an optional argument which specifies the reference label. However this doesn't seem to work in beamer.
