### ISSUE TITLE
Slides without a Title Picture

### ISSUE THREAD

**Issue by tthuem** [SoftVarE-Group/SlideTemplate#41]
When drafting slides, it would be great if one could also leave out the title picture completely. See hack in SPL slides:

https://github.com/SoftVarE-Group/Course-on-Software-Product-Lines/blob/main/slides/template/lecture.tex#L133

**Comment by Benno2000** [comment]
I added an option to create a title slide without a picture by using `\maketitle[none]` in 3c735de0803852203e0c3d2c2c6ce7f6abcd9ff9.

The only restriction that I see in this option is that you can't use "none" as a filename for your title pictures which I think should not be a problem :) We can also change "none" to something else like "plain" or "empty" if you want.

**Comment by tthuem** [comment]
I would prefer writing \maketitle[] because then I do not have to remember this keyword. Is this feasible?

**Comment by Benno2000** [comment]
I implemented this behavior in 790e286b45b47ee01fe2463bfbdff782dffea642. Now you can use `\maketitle[]`.

**Comment by Benno2000** [comment]
I merged this into release.
