### ISSUE TITLE
Large margin at the top of colorboxes with newer TeX Live versions

### ISSUE THREAD

**Issue by Benno2000** [SoftVarE-Group/SlideTemplate#58]
With TeX Live versions newer than 2022 (2023 at the moment), colorboxes like `definition` produce a larger margin above the content for a non-itemize or -enumerate text.

This behaviour seems to affect all tcolorboxes, but only in combination with our template. In a plain beamer document without the template, everything works fine.

**Comment by Benno2000** [comment]
I found the issue: The large space seems to come from setting the parskip of minipages (which also affects `tcolorbox`es):

`\newcommand{\@minipagerestore}{\setlength{\parskip}{1.5ex}} % use parskip also in minipages (also used for tcolorbox)`

Therefore the bug exists starting from the following commit: https://github.com/SoftVarE-Group/SlideTemplate/commit/c4d2c3f06cbfe703fd1ac0d7ba8fd742c653b2bf

However, I am not sure why this behaviour only exists for newer TeX Live versions and how it can be fixed yet.

**Comment by EagleoutIce** [comment]
I suspect it to be the consequence of the 5.x color patches of tcolorbox. If so, it should be a simple fix adding the parskip reset to the upper part of the boxes as well.

In a few hours I can have a look at this.

**Comment by tthuem** [comment]
Fixed in https://github.com/SoftVarE-Group/SlideTemplate/pull/59
