### ISSUE TITLE
Darkmode has wrong box-backgrounds

### ISSUE THREAD

**Issue by EagleoutIce** [SoftVarE-Group/SlideTemplate#60]
Potentially introduced by the merge of [29-customizable-colored-boxes](https://github.com/SoftVarE-Group/SlideTemplate/commit/c24fdb8ab4a4b8da3e09bb39d9b502ee65ebe7e2#diff-62432def5bf34832420a296e36fb456cb779fd3f8fd156ec1e3bdc0bb8cfe442L628-R630) the background of the boxes is hardcoded. This should be changed so they still have their old mixin behavior with the slide background.

**Comment by tthuem** [comment]
Fixed in https://github.com/SoftVarE-Group/SlideTemplate/pull/61
