### ISSUE TITLE
Create Separate Tex/PDF Files for Animated and Handout Version

### ISSUE THREAD

**Issue by tthuem** [SoftVarE-Group/SlideTemplate#7]
Would simplify the generation of both versions. I do have examples how we have done this for exercises and their solutions before.

**Comment by EagleoutIce** [comment]
There are several ways to do this:

1. We could use an external build script (i have several variants for larger and smaller projects)
2. We could rely on `\jobname` (e.g, if the jobname starts with `animated` or `handout`)
3. We could rely on macro definitions and simply set those (e.g. by writing to tex-files, the main animated one, and another handout version with roughly the following content:
   ```latex
   \PassOptionsToClass{handout}{beamer}
   \input{<animated.tex>}
   ```

**Comment by tthuem** [comment]
We are using external build scripts for most lectures now.
