### ISSUE TITLE
Add space at bottom of slides

### ISSUE THREAD

**Issue by Benno2000** [SoftVarE-Group/SlideTemplate#74]
When using bottom-aligned slides, there should be a white-space above the footer like there is one below the title when using the top alignment.

**Comment by Benno2000** [comment]
I added a space above the footer in https://github.com/SoftVarE-Group/SlideTemplate/commit/dcfd7c041dfc1d0a6ac3ec38a0553cd8ba52ca56, however, this also makes the frame content move upwards in standard (centered) mode. Does anyone know how I can insert the space only when bottom alignment (`[b]`) is used?

**Comment by EagleoutIce** [comment]
I am currently only on mobile but the best way is either to hack the corresponding key or to query the modified dimensions to balance.

https://github.com/josephwright/beamer/blob/20b8b7a50f364453fa40da3dbc6313650c843a63/base/beamerbaseframe.sty#L256

**Comment by Benno2000** [comment]
Thanks for the suggestion! If i redefine the key like that, it works:

```
\makeatletter
\define@key{beamerframe}{b}[true]{% bottom
  \beamer@frametopskip=0pt plus 1fill\relax%
  \beamer@framebottomskip=20pt\relax%
  \beamer@frametopskipautobreak=\beamer@frametopskip\relax%
  \beamer@framebottomskipautobreak=\beamer@framebottomskip\relax%
}
\makeatother
```

I wondered if there is a way to just change `\beamer@framebottomskip` without redefinig the whole key. Do you know if that is possible?

**Comment by EagleoutIce** [comment]
First of all such a modification is at least potentially hacky, as we modify the behavior of `beamer`.
Is there a good way? at least i am not aware of one.

If you really want to keep modifying, `define@key` is defined as:

```latex
\def\define@key#1#2{\@ifnextchar[{\KV@def{#1}{#2}}{\long\@namedef{KV@#1@#2}####1}}
```

in other words, the corresponding command name should resolve to `\KV@beamerframe@b` - you can modify that either with one of the many `patch` macros (like `patchcmd` of `etoolbox`).
However, i would suggest to at least use `\appto` to avoid potential future command modifications. 

My original idea was more like a test for the glue of `\beamer@framebottomskip` followed by the respective update.

**Comment by tthuem** [comment]
@Benno2000 Not sure whether the content moving upwards slightly in centered mode is actually a problem. We no define the valid area for slide content and centering in that area sounds fine to me. Do you have example screenshots where this is problematic and how it looks overall?

**Comment by Benno2000** [comment]
@EagleoutIce If I got that right, you mean to set the space using
```
\apptocmd{\KV@beamerframe@b}{
    \beamer@framebottomskip=20pt\relax%
}
```
?

I'm not really sure how you mean to test the glue.

**Comment by tthuem** [comment]
Is 20pt maybe too much? Do you have examples illustrating the padding to the top and bottom?

Does the same spacing also happen if there is another content (e.g., a picture)?

**Comment by EagleoutIce** [comment]
> @EagleoutIce If I got that right, you mean to set the space using
> 
> ```
> \apptocmd{\KV@beamerframe@b}{
>     \beamer@framebottomskip=20pt\relax%
> }
> ```
> 
Yes, although `\apptocmd` has two more arguments (for if the addition succeed or failed), so you may want to either suffix with `\relax\relax` or with corresponding actions (e.g. `\typeout{patching of \string\KV@beamerframe@b\space worked}` or a `\PackageWarning` in case of failure).

> 
> I'm not really sure how you mean to test the glue.

We have `\beamer@frametopskip=0pt plus 1fill\relax`. Hence, we can query the skip-register `\beamer@frametopskip` like this (note, that you have to query within a frame environment!):

```latex
\dimexpr\beamer@frametopskip % returns the default length: 0pt
\gluestretch\beamer@frametopskip % returns the stretch dimension (compare with stretchorder): 1pt
\gluestretchorder\beamer@frametopskip % the "infinity" order of the vector (stretch dimensions are vectors of multiple infinities, which allows 'filll' to stretch infinitely more than 'fill'... than 'fil'. For infinite stretch we search > 0): 2
\glueshrink\beamer@frametopskip % same for the shrinking (with minus, not given): 0pt
\glueshrinkorder\beamer@frametopskip % same as the \gluestretchorder: 0
```

Hence, either you test all of them by hand (using `\ifdim` and `\ifnum`) or you do some ugly closer-to-the-impl string-comparison like this:

```latex
% in the preamble, somewhere safe :D (it is possible without the \@tempskipa assignment, however, then you have to take care of zeros and expansions, ...)
\@tempskipa=0pt plus 1fill%
\edef\uulm@beamer@expectedbotskip{\the\@tempskipa}%

% within your test for the added vertical space (again could be done without the edef, but i find this more readable, furthermore it does not need string equality checks.
\edef\@tmp{\the\beamer@frametopskip}%
\ifx\@tmp\uulm@beamer@expectedbotskip Yes\else No\fi
```

**Comment by tthuem** [comment]
My feeling is that those changes can easily break existing slides. Shall we move it to the 1.0.0 release then?

**Comment by EagleoutIce** [comment]
They definitely change the layout for bottom aligned slides. The primary way of breaking that i can think of is for figures/text to move into the title area.

**Comment by Benno2000** [comment]
That's right, if users have slides with the content reaching down to the footer, this could cause issues.

In that case I would also suggest moving it to 1.0.0 as that release has breaking changes anyway.

**Comment by tthuem** [comment]
In case this is relevant, please create an issue here: https://github.com/SEatUPB/FancyBeamer/issues/new
