### ISSUE TITLE
Change column default for \contentoverview to one

### ISSUE THREAD

**Issue by Benno2000** [SoftVarE-Group/SlideTemplate#78]
The default for the number of columns in `\contentoverview[<number of columns>]` has been temporarily set to `2` in v0.3.0 in order to not break existing slides (see https://github.com/SoftVarE-Group/SlideTemplate/issues/75). As v1.0.0 is a breaking change anyway, the default should now be `1`.

**Comment by tthuem** [comment]
Done: https://github.com/SEatUPB/FancyBeamer/commit/842eece66923373c21968757a2853727c2d09bb1#diff-0904b9e4c150bf4252e7d3ca1fb17825541050877020fb048a18a9b20295a41c
